FROM nginx
LABEL maintainer="siakhooi@gmail.com"
LABEL name="Web Starter Kit - System Maintenance"
LABEL version="2023.04.02"

COPY www /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf
