name: basic-coming-soon

env:
  MY_DIRECTORY: basic/coming-soon
  MY_DOCKERFILE: Dockerfile 
  MY_REGISTRY: registry.hub.docker.com
  MY_REGISTRY_USER: ${{ secrets.MY_REGISTRY_USER }}
  MY_REGISTRY_PASSWORD: ${{ secrets.MY_REGISTRY_PASSWORD }}
  MY_TAG: siakhooi/starter-web:coming-soon

on:
  push:
    paths:
    - 'basic/coming-soon/**'

jobs:
  build_to_hub:
    name: Build Container and push image to Docker Hub
    runs-on: ubuntu-latest
    container: 
        image: docker:dind
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: chmod build script
        run: chmod +x .github/workflows/build-script.sh
      - name: run build script
        run: .github/workflows/build-script.sh
